### ISSUE TITLE
Unable to setup metaflow using Terraform

### ISSUE THREAD

**Issue by yudhiesh** [outerbounds/metaflow-tools#12]
When setting up the metaflow terraform code under `aws/terraform/metaflow` I am facing the following issue
```
╷
│ Error: no matching SecurityGroup found
│ 
│   with module.metaflow.module.metaflow-computation.data.aws_security_group.vpc_default,
│   on .terraform/modules/metaflow/modules/computation/data.tf line 11, in data "aws_security_group" "vpc_default":
│   11: data "aws_security_group" "vpc_default" {
│ 
╵
╷
│ Error: no matching SecurityGroup found
│ 
│   with module.metaflow.module.metaflow-metadata-service.data.aws_security_group.vpc_default,
│   on .terraform/modules/metaflow/modules/metadata-service/data.tf line 5, in data "aws_security_group" "vpc_default":
│    5: data "aws_security_group" "vpc_default" {
│ 
╵
```

Terraform version:
```
Terraform v1.1.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.75.1
+ provider registry.terraform.io/hashicorp/local v2.2.2
+ provider registry.terraform.io/hashicorp/random v3.1.2
```
I decided to check the resources that are stored within the `infra` directory after creating it and found that there is in fact a `aws_vpc` with the key `default_security_group_id` set.

**Comment by dworthman-indigo** [comment]
I also encountered this recently and was able to get past it by creating a project that uses the metaflow module/submodules. 

I was not ever able to `terraform init && terraform plan` successfully directly on the module, but I was for the project that used the module.

**Comment by yudhiesh** [comment]
@dworthman-indigo thanks will try that out. I ended up going with the CFN template instead with no issues whatsoever.

**Comment by oavdeev** [comment]
I couldn't repro the issue but the latest version of terraform module should fix this (it no longer relies on fetching default security group at all).
