### ISSUE TITLE
Accessing Metaflow after applying Terraform

### ISSUE THREAD

**Issue by johnseekins** [outerbounds/metaflow-tools#35]
Using the GCP terraform pattern, I was able to easily create a metaflow environment. Thanks!

I am a bit confused on how to access that environment now. If I'm reading my terraform state file correctly, no ingress to the GKE cluster is configured, but all the services are running there!

```
terraform $ grep ingress * -R
terraform.tfstate:                    "ingress": []
terraform.tfstate:                    "ingress": []
terraform.tfstate:                    "ingress": []
terraform.tfstate.backup:                  "cloud.google.com/neg": "{\"ingress\":true}"
terraform.tfstate.backup:                    "ingress": []
terraform.tfstate.backup:                  "cloud.google.com/neg": "{\"ingress\":true}"
terraform.tfstate.backup:                    "ingress": []
terraform.tfstate.backup:                  "cloud.google.com/neg": "{\"ingress\":true}"
terraform.tfstate.backup:                    "ingress": []
```

I assume I'm just missing something obvious here, but what is the next step in accessing my newly created cluster?

(As a side note, the GCP terraform deploy doesn't work correctly with Terraform Cloud - likely because it assumes some local connections with kubectl that Terraform Cloud can't really have)

**Comment by jackie-ob** [comment]
Re: TF cloud, I think your assumption is correct.  Yes we do need to use certain tools.  We have heard that the recommendation is to actually install those tools "inline" within the terraform apply itself, somehow (local-execs and what not).

Re: Ingress, you are correct that there is no ingress.  Ingress setup can be opinionated (for good reasons, like security posture, running cost, etc), and so it is left alone.  To access this cluster kubectl portforwarding is required.

I hope this helps unblock you.  To continue to get a quick response please consider joining our [slack channel](https://join.slack.com/t/outerbounds-community/shared_invite/zt-1rniq6c6o-UbC5sPp7Fulo0Qge1me58A).
