### ISSUE TITLE
Terraform ui_certificate_arn variable required.

### ISSUE THREAD

**Issue by msiers** [outerbounds/metaflow-tools#6]
Trying to use the use the instructions from the README.md file and the terraform-aws-metaflow module now requires the "ui_certificate_arn" variable to be set.  Defaulting the variable to an empty string causes errors when applying the terraform to create the infrastructure.

Is there any way to disable this requirement for a "ui_certificate_arn"?

**Comment by oavdeev** [comment]
AWS ALB listener that we use for UI requires a SSL certificate, but the whole UI module can be made optional (see https://github.com/outerbounds/terraform-aws-metaflow/pull/8 )

**Comment by oavdeev** [comment]
closing since UI is now optional
